### PR TITLE
Hide Apple Pay component by default and display it only if method is available

### PR DESCRIPTION
**Pull request by dimitriBouteille**
## Summary

Hide Apple Pay component by default and display it only if method is available. Avoids front-side edge effects if the component is not displayed.

I also add an `onNotAvailable` function to avoid having to copy the whole function in case of modification in a theme.

**Fixed issue**:  #54

### CODE REVIEW

**Review by hossam-adyen — APPROVED** [review]

**Comment by dimitriBouteille** [comment]
@hossam-adyen You know when this PR will be merged on main ?

**Review by candemiralp — APPROVED** [review]

**Comment by hossam-adyen** [comment]
Hi @dimitriBouteille, this would be release more likely next week

**Comment by dimitriBouteille** [comment]
Hi @hossam-adyen Do you know when a tag or release will be created with the latest fixes?

**Comment by hossam-adyen** [comment]
Hi @dimitriBouteille, it has ben released today in version 1.2.0

**Pull request merged**
